/*
 * ControlePonto_v2.0
 * Cedup Hermmann Hering 20/04/19
 * @MecSystem
*/
package Activitys;

import java.awt.Cursor;

/**
 *
 * @author LOL
 */
public class actAlert extends javax.swing.JDialog {

    /**
     * Creates new form actAviso
     */
    public actAlert() {
        initComponents();
        this.setLocationRelativeTo(null);   //Centraliza a Tela
        imgBackground.requestFocus();
        btnOkay.setVisible(false);
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOkay = new javax.swing.JLabel();
        imgOkay = new javax.swing.JLabel();
        lbMsg = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOkay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOkay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoOkayAviso2.jpg"))); // NOI18N
        btnOkay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkayMouseExited(evt);
            }
        });
        getContentPane().add(btnOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 450, -1));

        imgOkay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgOkay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoOkayAviso.jpg"))); // NOI18N
        imgOkay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgOkayMouseEntered(evt);
            }
        });
        getContentPane().add(imgOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 450, -1));

        lbMsg.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        lbMsg.setForeground(new java.awt.Color(255, 255, 255));
        lbMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMsg.setText("<html><p align=\"center\">Voce não preencheu<br>algum campo</p></html>");
        getContentPane().add(lbMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 448, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/Tela-Aviso.jpg"))); // NOI18N
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgOkayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgOkayMouseEntered
        imgOkay.setVisible(false);
        btnOkay.setVisible(true);
    }//GEN-LAST:event_imgOkayMouseEntered

    private void btnOkayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseExited
        imgOkay.setVisible(true);
        btnOkay.setVisible(false);
    }//GEN-LAST:event_btnOkayMouseExited

    private void btnOkayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseEntered
        btnOkay.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnOkayMouseEntered

    private void btnOkayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnOkayMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actAlert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnOkay;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgOkay;
    public javax.swing.JLabel lbMsg;
    // End of variables declaration//GEN-END:variables
}
