/*
 * ControlePonto_v2.0
 * Cedup Hermmann Hering 20/04/19
 * @MecSystem
 */
package Activitys;

import java.awt.Color;
import java.awt.Cursor;
import mecsystem.Classes.Function;

/**
 *
 * @author LOL
 */
public class actCreateFunction extends javax.swing.JDialog {

    /**
     * Creates new form actLogin
     */
    public actCreateFunction() {
        initComponents();
        this.setModal(true);
        Desfoque.setVisible(false);
        this.setLocationRelativeTo(null);   //Centraliza a Tela
        imgBackground.requestFocus();
        btnPronto.setVisible(false);
        Desfoque.setBackground(new Color(0, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desfoque = new javax.swing.JPanel();
        btnPronto = new javax.swing.JLabel();
        imgPronto = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        edtFunction = new javax.swing.JTextField();
        edtCBO = new javax.swing.JFormattedTextField();
        lblTitle = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Desfoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1028, 720));

        btnPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoProntoLogin2.jpg"))); // NOI18N
        btnPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProntoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProntoMouseExited(evt);
            }
        });
        getContentPane().add(btnPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        imgPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoProntoLogin.jpg"))); // NOI18N
        imgPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgProntoMouseEntered(evt);
            }
        });
        getContentPane().add(imgPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        btnSair.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Voltar");
        btnSair.setToolTipText("Voltar");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        edtFunction.setBackground(new java.awt.Color(51, 170, 236));
        edtFunction.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtFunction.setForeground(new java.awt.Color(255, 255, 255));
        edtFunction.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtFunction.setText("Nome da Função");
        edtFunction.setToolTipText("Nome da Função");
        edtFunction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtFunction.setOpaque(false);
        edtFunction.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtFunctionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtFunctionFocusLost(evt);
            }
        });
        getContentPane().add(edtFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 320, 260, 40));

        edtCBO.setBackground(new java.awt.Color(51, 170, 236));
        edtCBO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtCBO.setForeground(new java.awt.Color(255, 255, 255));
        try {
            edtCBO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCBO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCBO.setToolTipText("CBO");
        edtCBO.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCBO.setOpaque(false);
        getContentPane().add(edtCBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 245, 260, 40));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 40)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Cadastro de Função");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 828, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/TelasCRUD1.jpg"))); // NOI18N
        imgBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBackgroundMouseClicked(evt);
            }
        });
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtFunctionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtFunctionFocusGained
        if (edtFunction.getText().equals("Nome da Função")) {
            edtFunction.setText("");
        }
    }//GEN-LAST:event_edtFunctionFocusGained

    private void edtFunctionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtFunctionFocusLost
        if (edtFunction.getText().trim().isEmpty()) {
            edtFunction.setText("Nome da Função");
        }
    }//GEN-LAST:event_edtFunctionFocusLost

    private void btnProntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseClicked
        if (doValidations()) {
            Function f = new Function();
            f.setCBO(edtCBO.getText());
            f.setFunctionName(edtFunction.getText());
            if (f.Create()) {
                actAlert alert = new actAlert();
                alert.lbMsg.setText("<html><p align=\"center\">Função cadastrada com sucesso!</p></html>");
                alert.setVisible(true);
                edtCBO.setText("");
                edtFunction.setText("Nome da Função");
            } else {
                actAlert alert = new actAlert();
                alert.lbMsg.setText("<html><p align=\"center\">Esse Nome já está <br> Cadastrado para outra Função!</p></html>");
                alert.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnProntoMouseClicked

    private void btnProntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseExited
        btnPronto.setVisible(false);
        imgPronto.setVisible(true);
    }//GEN-LAST:event_btnProntoMouseExited

    private void imgProntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgProntoMouseEntered
        imgPronto.setVisible(false);
        btnPronto.setVisible(true);
        btnPronto.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_imgProntoMouseEntered

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSairMouseEntered

    private void imgBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBackgroundMouseClicked
        imgBackground.requestFocus();
    }//GEN-LAST:event_imgBackgroundMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        Desfoque.setVisible(true);
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Desfoque.setVisible(false);

    }//GEN-LAST:event_formWindowGainedFocus

    public boolean CheckIsEmpty() {
        if ((edtFunction.getText().trim().isEmpty() || edtFunction.getText().equals("Nome da Função"))) {
            return false;
        }  else if (edtCBO.getText().trim().length() != 7) {
            return false;
        }
        return true;
    }

    public boolean CheckIfExists() {
        Function f = new Function();
        f.setCBO(edtCBO.getText());
        f.ReadByCBO();
        return f.getFunctionName() == null;
    }

    public boolean doValidations() {
        if (!CheckIsEmpty()) {
            new actAlert().setVisible(true);
            return false;
        } else if (!CheckIfExists()) {
            actAlert a = new actAlert();
            a.lbMsg.setText("<html><p align='center'>Esse CBO já está <br> Cadastrado para outra Função!</p></html>");
            a.setVisible(true);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actCreateFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actCreateFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actCreateFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actCreateFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actCreateFunction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desfoque;
    private javax.swing.JLabel btnPronto;
    private javax.swing.JLabel btnSair;
    private javax.swing.JFormattedTextField edtCBO;
    private javax.swing.JTextField edtFunction;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgPronto;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
