/*
 * ControlePonto_v2.0
 * Cedup Hermmann Hering 20/04/19
 * @MecSystem
 */
package Activitys;

import java.awt.Color;
import java.awt.Cursor;
import mecsystem.Classes.Function;
import mecsystem.Classes.Point;

/**
 *
 * @author LOL
 */
public class actCreatePoint extends javax.swing.JDialog {

    /**
     * Creates new form actLogin
     */
    public actCreatePoint() {
        initComponents();
        this.setModal(true);
        Desfoque.setVisible(false);
        this.setLocationRelativeTo(null);   //Centraliza a Tela
        imgBackground.requestFocus();
        btnPronto.setVisible(false);
        Desfoque.setBackground(new Color(0, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desfoque = new javax.swing.JPanel();
        btnPronto = new javax.swing.JLabel();
        imgPronto = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        edtCode = new javax.swing.JTextField();
        edtLocale = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Desfoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1028, 720));

        btnPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoProntoLogin2.jpg"))); // NOI18N
        btnPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProntoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProntoMouseExited(evt);
            }
        });
        getContentPane().add(btnPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        imgPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoProntoLogin.jpg"))); // NOI18N
        imgPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgProntoMouseEntered(evt);
            }
        });
        getContentPane().add(imgPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        btnSair.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Voltar");
        btnSair.setToolTipText("Voltar");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        edtCode.setBackground(new java.awt.Color(51, 170, 236));
        edtCode.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCode.setForeground(new java.awt.Color(255, 255, 255));
        edtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCode.setText("Código");
        edtCode.setToolTipText("Nome da Função");
        edtCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtCode.setOpaque(false);
        edtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCodeFocusLost(evt);
            }
        });
        getContentPane().add(edtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 245, 260, 40));

        edtLocale.setBackground(new java.awt.Color(51, 170, 236));
        edtLocale.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtLocale.setForeground(new java.awt.Color(255, 255, 255));
        edtLocale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtLocale.setText("Local");
        edtLocale.setToolTipText("Nome da Função");
        edtLocale.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtLocale.setOpaque(false);
        edtLocale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtLocaleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtLocaleFocusLost(evt);
            }
        });
        getContentPane().add(edtLocale, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 320, 260, 40));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 40)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Cadastro de Ponto");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 828, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/TelasCRUD1.jpg"))); // NOI18N
        imgBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBackgroundMouseClicked(evt);
            }
        });
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtLocaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLocaleFocusGained
        if (edtLocale.getText().equals("Local")) {
            edtLocale.setText("");
        }
    }//GEN-LAST:event_edtLocaleFocusGained

    private void edtLocaleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLocaleFocusLost
        if (edtLocale.getText().trim().isEmpty()) {
            edtLocale.setText("Local");
        }
    }//GEN-LAST:event_edtLocaleFocusLost

    private void btnProntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseClicked
        if (doValidations()) {
            Point p = new Point();
            p.setCode(Integer.parseInt(edtCode.getText()));
            p.setLocale(edtLocale.getText());
            if(p.Create()){
                actAlert a = new actAlert();
                a.lbMsg.setText("<html><p align=\"center\">Ponto cadastrado com sucesso!</p></html>");
                a.setVisible(true);
                edtCode.setText("Código");
                edtLocale.setText("Local");
            }
        }
    }//GEN-LAST:event_btnProntoMouseClicked

    private void btnProntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseExited
        btnPronto.setVisible(false);
        imgPronto.setVisible(true);
    }//GEN-LAST:event_btnProntoMouseExited

    private void imgProntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgProntoMouseEntered
        imgPronto.setVisible(false);
        btnPronto.setVisible(true);
        btnPronto.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_imgProntoMouseEntered

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSairMouseEntered

    private void imgBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBackgroundMouseClicked
        imgBackground.requestFocus();
    }//GEN-LAST:event_imgBackgroundMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        Desfoque.setVisible(true);
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Desfoque.setVisible(false);

    }//GEN-LAST:event_formWindowGainedFocus

    private void edtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodeFocusGained
        if(edtCode.getText().equals("Código"))
            edtCode.setText("");
    }//GEN-LAST:event_edtCodeFocusGained

    private void edtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodeFocusLost
        if(edtCode.getText().equals(""))
            edtCode.setText("Código");
    }//GEN-LAST:event_edtCodeFocusLost

    public boolean CheckIsEmpty() {
        if ((edtLocale.getText().trim().isEmpty() || edtLocale.getText().equals("Local"))) {
            return false;
        }  else if ((edtCode.getText().trim().isEmpty() || edtCode.getText().equals("Código"))) {
            return false;
        }
        return true;
    }
    
    public boolean CheckNumber(String TestingNumber) {
        int Number = 0;
        try {
            Number = Integer.parseInt(TestingNumber);
        } catch (NumberFormatException e) {
            return true;
        }
        return false;
    }

    

    public boolean doValidations() {
        if (!CheckIsEmpty()) {
            new actAlert().setVisible(true);
            return false;
        } else if (CheckNumber(edtCode.getText())){
           actAlert a = new actAlert();
           a.lbMsg.setText("<html><p align=\"center\">O Código <br> precisa ser um Número!</p></html>");
           a.setVisible(true);
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actCreatePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actCreatePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actCreatePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actCreatePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actCreatePoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desfoque;
    private javax.swing.JLabel btnPronto;
    private javax.swing.JLabel btnSair;
    private javax.swing.JTextField edtCode;
    private javax.swing.JTextField edtLocale;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgPronto;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
