/*
 * ControlePonto_v2.0
 * Cedup Hermmann Hering 20/04/19
 * @MecSystem
 */
package Activitys;

import java.awt.Color;
import java.awt.Cursor;
import mecsystem.Classes.Point;

/**
 *
 * @author LOL
 */
public class actDeletePoint extends javax.swing.JDialog {

    /**
     * Creates new form actLogin
     */
    int SelectedId;

    public actDeletePoint() {
        initComponents();
        this.setModal(true);
        Desfoque.setVisible(false);
        this.setLocationRelativeTo(null);   //Centraliza a Tela
        imgBackground.requestFocus();
        btnPopUp.setVisible(false);
        btnPronto.setVisible(false);
        Desfoque.setBackground(new Color(0, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desfoque = new javax.swing.JPanel();
        btnPronto = new javax.swing.JLabel();
        btnPopUp = new javax.swing.JLabel();
        imgPronto = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        imgPopUp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        edtSearch = new javax.swing.JTextField();
        edtCode = new javax.swing.JTextField();
        edtLocal = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Desfoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1028, 720));

        btnPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoProntoLogin2.jpg"))); // NOI18N
        btnPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProntoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProntoMouseExited(evt);
            }
        });
        getContentPane().add(btnPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        btnPopUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/popup2.jpg"))); // NOI18N
        btnPopUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPopUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPopUpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPopUpMouseExited(evt);
            }
        });
        getContentPane().add(btnPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 115, -1, -1));

        imgPronto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/BotaoProntoLogin.jpg"))); // NOI18N
        imgPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgProntoMouseEntered(evt);
            }
        });
        getContentPane().add(imgPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        btnSair.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Voltar");
        btnSair.setToolTipText("Voltar");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        imgPopUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/popup.jpg"))); // NOI18N
        imgPopUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgPopUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgPopUpMouseEntered(evt);
            }
        });
        getContentPane().add(imgPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 115, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/curbatura.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 106, -1, -1));

        edtSearch.setBackground(new java.awt.Color(51, 170, 236));
        edtSearch.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtSearch.setForeground(new java.awt.Color(255, 255, 255));
        edtSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtSearch.setText("Pesquisar por Código");
        edtSearch.setToolTipText("Pesquisar");
        edtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtSearch.setOpaque(false);
        edtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtSearchFocusGained(evt);
            }
        });
        edtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(edtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 115, 428, 40));

        edtCode.setEditable(false);
        edtCode.setBackground(new java.awt.Color(51, 170, 236));
        edtCode.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCode.setForeground(new java.awt.Color(255, 255, 255));
        edtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCode.setText("Código");
        edtCode.setToolTipText("Código");
        edtCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtCode.setOpaque(false);
        edtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCodeFocusLost(evt);
            }
        });
        getContentPane().add(edtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 245, 260, 40));

        edtLocal.setEditable(false);
        edtLocal.setBackground(new java.awt.Color(51, 170, 236));
        edtLocal.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtLocal.setForeground(new java.awt.Color(255, 255, 255));
        edtLocal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtLocal.setText("Local");
        edtLocal.setToolTipText("Local");
        edtLocal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtLocal.setOpaque(false);
        edtLocal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtLocalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtLocalFocusLost(evt);
            }
        });
        getContentPane().add(edtLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 320, 260, 40));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 40)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Deletar Ponto");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 828, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/TelasCRUD1.jpg"))); // NOI18N
        imgBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBackgroundMouseClicked(evt);
            }
        });
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtLocalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLocalFocusGained
        if (edtLocal.getText().equals("Local")) {
            edtLocal.setText("");
        }
    }//GEN-LAST:event_edtLocalFocusGained

    private void edtLocalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLocalFocusLost
        if (edtLocal.getText().trim().isEmpty()) {
            edtLocal.setText("Local");
        }
    }//GEN-LAST:event_edtLocalFocusLost

    private void btnProntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseClicked
        Point p = new Point();
            p.setCode(Integer.parseInt(edtCode.getText()));
            if(p.Delete()){
                actAlert alert = new actAlert();
                alert.lbMsg.setText("<html><p align=\"center\">Ponto excluído com sucesso!</p></html>");
                alert.setVisible(true);
                setToNormal();
            }
    }//GEN-LAST:event_btnProntoMouseClicked

    private void btnProntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseExited
        btnPronto.setVisible(false);
        imgPronto.setVisible(true);
    }//GEN-LAST:event_btnProntoMouseExited

    private void imgProntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgProntoMouseEntered
        if (!edtLocal.getText().equals("Local")) {
            imgPronto.setVisible(false);
            btnPronto.setVisible(true);
            btnPronto.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_imgProntoMouseEntered

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSairMouseEntered

    private void imgBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBackgroundMouseClicked
        imgBackground.requestFocus();
    }//GEN-LAST:event_imgBackgroundMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        Desfoque.setVisible(true);
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Desfoque.setVisible(false);

    }//GEN-LAST:event_formWindowGainedFocus

    private void imgPopUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPopUpMouseEntered
        btnPopUp.setVisible(true);
        imgPopUp.setVisible(false);
    }//GEN-LAST:event_imgPopUpMouseEntered

    private void btnPopUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPopUpMouseExited
        btnPopUp.setVisible(false);
        imgPopUp.setVisible(true);
    }//GEN-LAST:event_btnPopUpMouseExited

    private void edtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusGained
        if (edtSearch.getText().equals("Pesquisar por Código")) {
            edtSearch.setText("");
        }
    }//GEN-LAST:event_edtSearchFocusGained

    private void edtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSearchActionPerformed
        getData(edtSearch.getText());
    }//GEN-LAST:event_edtSearchActionPerformed

    private void edtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodeFocusGained
        if (edtCode.getText().equals("Código")) {
            edtCode.setText("");
        }
    }//GEN-LAST:event_edtCodeFocusGained

    private void edtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodeFocusLost
        if (edtCode.getText().trim().isEmpty()) {
            edtCode.setText("Código");
        }
    }//GEN-LAST:event_edtCodeFocusLost

    private void btnPopUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPopUpMouseClicked
        actReadPoint a = new actReadPoint();
        a.setVisible(true);
        if(a.Verify){
            edtSearch.setText(a.SelectedParameter);
            getData(edtSearch.getText());
        }
    }//GEN-LAST:event_btnPopUpMouseClicked



    public void setToNormal() {
        edtCode.setText("Código");
        edtLocal.setText("Nome da Função");
        edtSearch.setText("");
        edtSearch.requestFocus();
    }

    public void getData(String parSearch) {
        Point p = new Point();
        try {
            p.setCode(Integer.parseInt(edtSearch.getText()));
        } catch (NumberFormatException ex) {
            p.setCode(0);
        }

        p.ReadByCode();
        if (p.getLocale() != null) {
            edtLocal.setText(p.getLocale());
            SelectedId = p.getCode();
            edtCode.setText(Integer.toString(SelectedId));
        } else {
            actAlert a = new actAlert();
            a.lbMsg.setText("<html><p align\"center\">Ponto não encontrado!</p></html>");
            a.setVisible(true);
            setToNormal();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actDeletePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actDeletePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actDeletePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actDeletePoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actDeletePoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desfoque;
    private javax.swing.JLabel btnPopUp;
    private javax.swing.JLabel btnPronto;
    private javax.swing.JLabel btnSair;
    private javax.swing.JTextField edtCode;
    private javax.swing.JTextField edtLocal;
    private javax.swing.JTextField edtSearch;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgPopUp;
    private javax.swing.JLabel imgPronto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
