/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activitys;

import java.awt.Color;
import java.awt.Cursor;
import static java.lang.Thread.sleep;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import mecsystem.Classes.Company;
import mecsystem.Classes.Admin;
import mecsystem.Classes.Point;

/**
 *
 * @author LOL
 */
public class actFirstLogin extends javax.swing.JFrame {

    /**
     * Creates new form actFirstLogin
     */
    public actFirstLogin() {
        initComponents();
        background.requestFocus();
        lblBackground.setBackground(new Color(0, 0, 0, 100));
        lblBackground.setVisible(false);
        edtCNPJ.setBackground(new Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackground = new javax.swing.JLabel();
        pnBackground = new javax.swing.JPanel();
        lblCNPJ = new javax.swing.JLabel();
        edtCNPJ = new javax.swing.JFormattedTextField();
        edtNumber = new javax.swing.JTextField();
        edtCompanyName = new javax.swing.JTextField();
        edtStreet = new javax.swing.JTextField();
        pnPronto = new javax.swing.JPanel();
        btnPronto = new javax.swing.JLabel();
        pnAdmin = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        edtCPF = new javax.swing.JFormattedTextField();
        edtPassword = new javax.swing.JTextField();
        edtLogin = new javax.swing.JTextField();
        pnPronto1 = new javax.swing.JPanel();
        btnPronto1 = new javax.swing.JLabel();
        pnPoint = new javax.swing.JPanel();
        edtLocation = new javax.swing.JTextField();
        edtCode = new javax.swing.JTextField();
        pnPronto2 = new javax.swing.JPanel();
        btnPronto2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        lblNotice = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackground.setOpaque(true);
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1028, 720));

        pnBackground.setBackground(new java.awt.Color(204, 51, 255));
        pnBackground.setOpaque(false);
        pnBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCNPJ.setBackground(new java.awt.Color(61, 149, 223));
        lblCNPJ.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        lblCNPJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCNPJ.setText("CNPJ");
        lblCNPJ.setOpaque(true);
        pnBackground.add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 47, 120, 25));

        edtCNPJ.setBorder(null);
        edtCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        try {
            edtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCNPJ.setToolTipText("CNPJ");
        edtCNPJ.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCNPJ.setOpaque(false);
        edtCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCNPJFocusLost(evt);
            }
        });
        pnBackground.add(edtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, 429, 40));

        edtNumber.setBackground(new java.awt.Color(60, 158, 221));
        edtNumber.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtNumber.setForeground(new java.awt.Color(255, 255, 255));
        edtNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtNumber.setText("Número");
        edtNumber.setToolTipText("Número");
        edtNumber.setBorder(null);
        edtNumber.setOpaque(false);
        edtNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtNumberFocusLost(evt);
            }
        });
        pnBackground.add(edtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 110, 429, 40));

        edtCompanyName.setBackground(new java.awt.Color(60, 158, 221));
        edtCompanyName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCompanyName.setForeground(new java.awt.Color(255, 255, 255));
        edtCompanyName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCompanyName.setText("Nome da Empresa");
        edtCompanyName.setToolTipText("Nome da Empresa");
        edtCompanyName.setBorder(null);
        edtCompanyName.setOpaque(false);
        edtCompanyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCompanyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCompanyNameFocusLost(evt);
            }
        });
        pnBackground.add(edtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 40, 429, 40));

        edtStreet.setBackground(new java.awt.Color(60, 158, 221));
        edtStreet.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtStreet.setForeground(new java.awt.Color(255, 255, 255));
        edtStreet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtStreet.setText("Rua");
        edtStreet.setToolTipText("Rua");
        edtStreet.setBorder(null);
        edtStreet.setOpaque(false);
        edtStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtStreetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtStreetFocusLost(evt);
            }
        });
        pnBackground.add(edtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 110, 429, 40));

        pnPronto.setBackground(new java.awt.Color(112, 207, 234));
        pnPronto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnPronto.setOpaque(false);

        btnPronto.setBackground(new java.awt.Color(112, 207, 234));
        btnPronto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        btnPronto.setForeground(new java.awt.Color(255, 255, 255));
        btnPronto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPronto.setText("Pronto!");
        btnPronto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProntoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProntoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProntoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnProntoLayout = new javax.swing.GroupLayout(pnPronto);
        pnPronto.setLayout(pnProntoLayout);
        pnProntoLayout.setHorizontalGroup(
            pnProntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPronto, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        pnProntoLayout.setVerticalGroup(
            pnProntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPronto, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        pnBackground.add(pnPronto, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 200, 150, 50));

        getContentPane().add(pnBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 928, 300));

        pnAdmin.setBackground(new java.awt.Color(204, 51, 255));
        pnAdmin.setOpaque(false);
        pnAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCPF.setBackground(new java.awt.Color(61, 149, 223));
        lblCPF.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCPF.setText("CPF");
        lblCPF.setOpaque(true);
        pnAdmin.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 128, 25));

        edtCPF.setBorder(null);
        edtCPF.setForeground(new java.awt.Color(255, 255, 255));
        try {
            edtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCPF.setToolTipText("CPF");
        edtCPF.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCPF.setOpaque(false);
        edtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCPFFocusGained(evt);
            }
        });
        pnAdmin.add(edtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 428, 40));

        edtPassword.setBackground(new java.awt.Color(60, 158, 221));
        edtPassword.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtPassword.setForeground(new java.awt.Color(255, 255, 255));
        edtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtPassword.setText("Senha");
        edtPassword.setToolTipText("Senha");
        edtPassword.setBorder(null);
        edtPassword.setOpaque(false);
        edtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtPasswordFocusLost(evt);
            }
        });
        pnAdmin.add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 428, 40));

        edtLogin.setBackground(new java.awt.Color(60, 158, 221));
        edtLogin.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtLogin.setForeground(new java.awt.Color(255, 255, 255));
        edtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtLogin.setText("Login");
        edtLogin.setToolTipText("Login");
        edtLogin.setBorder(null);
        edtLogin.setOpaque(false);
        edtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtLoginFocusLost(evt);
            }
        });
        pnAdmin.add(edtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 428, 40));

        pnPronto1.setBackground(new java.awt.Color(112, 207, 234));
        pnPronto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnPronto1.setOpaque(false);

        btnPronto1.setBackground(new java.awt.Color(112, 207, 234));
        btnPronto1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        btnPronto1.setForeground(new java.awt.Color(255, 255, 255));
        btnPronto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPronto1.setText("Pronto!");
        btnPronto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPronto1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPronto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPronto1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnPronto1Layout = new javax.swing.GroupLayout(pnPronto1);
        pnPronto1.setLayout(pnPronto1Layout);
        pnPronto1Layout.setHorizontalGroup(
            pnPronto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPronto1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        pnPronto1Layout.setVerticalGroup(
            pnPronto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPronto1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        pnAdmin.add(pnPronto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 220, 150, 50));

        getContentPane().add(pnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 215, 728, 300));

        pnPoint.setBackground(new java.awt.Color(204, 51, 255));
        pnPoint.setOpaque(false);
        pnPoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtLocation.setBackground(new java.awt.Color(60, 158, 221));
        edtLocation.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtLocation.setForeground(new java.awt.Color(255, 255, 255));
        edtLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtLocation.setText("Local");
        edtLocation.setToolTipText("Local");
        edtLocation.setBorder(null);
        edtLocation.setOpaque(false);
        edtLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtLocationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtLocationFocusLost(evt);
            }
        });
        pnPoint.add(edtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 428, 40));

        edtCode.setBackground(new java.awt.Color(60, 158, 221));
        edtCode.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtCode.setForeground(new java.awt.Color(255, 255, 255));
        edtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCode.setText("Código do Aparelho");
        edtCode.setToolTipText("Código do Aparelho");
        edtCode.setBorder(null);
        edtCode.setOpaque(false);
        edtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCodeFocusLost(evt);
            }
        });
        pnPoint.add(edtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 428, 40));

        pnPronto2.setBackground(new java.awt.Color(112, 207, 234));
        pnPronto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnPronto2.setOpaque(false);

        btnPronto2.setBackground(new java.awt.Color(112, 207, 234));
        btnPronto2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        btnPronto2.setForeground(new java.awt.Color(255, 255, 255));
        btnPronto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPronto2.setText("Pronto!");
        btnPronto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPronto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPronto2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPronto2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnPronto2Layout = new javax.swing.GroupLayout(pnPronto2);
        pnPronto2.setLayout(pnPronto2Layout);
        pnPronto2Layout.setHorizontalGroup(
            pnPronto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPronto2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        pnPronto2Layout.setVerticalGroup(
            pnPronto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPronto2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        pnPoint.add(pnPronto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 220, 150, 50));

        getContentPane().add(pnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 728, 300));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Olá, é a sua primeira vez aqui...");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 928, -1));

        lblSubTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("Para começar me informe os dados de sua empresa");
        getContentPane().add(lblSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1028, -1));

        btnExit.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Sair");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 40, -1));

        lblNotice.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        lblNotice.setForeground(new java.awt.Color(255, 255, 255));
        lblNotice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotice.setText("*Lembrete: Você pode cadastrar outros aparelhos depois.");
        getContentPane().add(lblNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 625, 1028, -1));

        background.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1028, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnProntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseClicked
        if (doCompanyValidations()) {
            Company c = new Company();
            c.setNameCompany(edtCompanyName.getText());
            c.setCPNJ(edtCNPJ.getText());
            c.setNumberCompany(edtNumber.getText());
            c.setStreetName(edtStreet.getText());
            if (c.Create()) {
                lblTitle.setText("Agora vamos cadastrar um Administrador!");
                lblSubTitle.setText("Informe seus dados");
                doAnimation(1);
            }
        }
    }//GEN-LAST:event_btnProntoMouseClicked

    private void btnProntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseEntered
        btnPronto.setForeground(new Color(220, 255, 255));
        pnPronto.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnProntoMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        doAnimation(0);
    }//GEN-LAST:event_formWindowOpened

    private void edtCompanyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCompanyNameFocusGained
        if (edtCompanyName.getText().equals("Nome da Empresa")) {
            edtCompanyName.setText("");
        }
    }//GEN-LAST:event_edtCompanyNameFocusGained

    private void edtCompanyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCompanyNameFocusLost
        if (edtCompanyName.getText().trim().isEmpty()) {
            edtCompanyName.setText("Nome da Empresa");
        }
    }//GEN-LAST:event_edtCompanyNameFocusLost

    private void edtStreetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtStreetFocusGained
        if (edtStreet.getText().equals("Rua")) {
            edtStreet.setText("");
        }
    }//GEN-LAST:event_edtStreetFocusGained

    private void edtStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtStreetFocusLost
        if (edtStreet.getText().trim().isEmpty()) {
            edtStreet.setText("Rua");
        }
    }//GEN-LAST:event_edtStreetFocusLost

    private void edtNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNumberFocusGained
        if (edtNumber.getText().equals("Número")) {
            edtNumber.setText("");
        }
    }//GEN-LAST:event_edtNumberFocusGained

    private void edtNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNumberFocusLost
        if (edtNumber.getText().trim().isEmpty()) {
            edtNumber.setText("Número");
        }
    }//GEN-LAST:event_edtNumberFocusLost

    private void btnProntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProntoMouseExited
        btnPronto.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnProntoMouseExited

    private void edtCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCNPJFocusGained
        if (edtCNPJ.getText().equals("  .   .   /    -  ")) {
            lblCNPJ.setVisible(false);
        }

    }//GEN-LAST:event_edtCNPJFocusGained

    private void edtCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCNPJFocusLost
        if ((edtCNPJ.getText().equals("  .   .   /    -  ")) || (edtCNPJ.getText().trim().length() != 20)) {
            edtCNPJ.setText("  .   .   /    -  ");
        }
    }//GEN-LAST:event_edtCNPJFocusLost

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        lblBackground.setVisible(true);
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        lblBackground.setVisible(false);
    }//GEN-LAST:event_formWindowGainedFocus

    private void edtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCPFFocusGained
        lblCPF.setVisible(false);
    }//GEN-LAST:event_edtCPFFocusGained

    private void edtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPasswordFocusGained
        if (edtPassword.getText().equals("Senha")) {
            edtPassword.setText("");
        }
    }//GEN-LAST:event_edtPasswordFocusGained

    private void edtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPasswordFocusLost
        if (edtPassword.getText().trim().isEmpty()) {
            edtPassword.setText("Senha");
        }
    }//GEN-LAST:event_edtPasswordFocusLost

    private void edtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLoginFocusGained
        if (edtLogin.getText().equals("Login")) {
            edtLogin.setText("");
        }
    }//GEN-LAST:event_edtLoginFocusGained

    private void edtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLoginFocusLost
        if (edtLogin.getText().trim().isEmpty()) {
            edtLogin.setText("Login");
        }
    }//GEN-LAST:event_edtLoginFocusLost

    private void btnPronto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPronto1MouseClicked
        if (doAdminValidations()) {
            Admin a = new Admin();
            a.setLoginAdmin(edtLogin.getText());
            a.setPassword(edtPassword.getText());
            a.setCPF(edtCPF.getText());
            if (a.Create()) {
                lblTitle.setText("Calma, estamos quase prontos...");
                lblSubTitle.setText("Informe os dados do seu Ponto Principal");
                doAnimation(2);
            } 
        }
    }//GEN-LAST:event_btnPronto1MouseClicked

    private void btnPronto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPronto1MouseEntered
        btnPronto1.setForeground(new Color(220, 255, 255));
        pnPronto1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPronto1MouseEntered

    private void btnPronto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPronto1MouseExited
        btnPronto1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnPronto1MouseExited

    private void edtLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLocationFocusGained
        if (edtLocation.getText().equals("Local")) {
            edtLocation.setText("");
        }
    }//GEN-LAST:event_edtLocationFocusGained

    private void edtLocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtLocationFocusLost
        if (edtLocation.getText().equals("")) {
            edtLocation.setText("Local");
        }
    }//GEN-LAST:event_edtLocationFocusLost

    private void edtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodeFocusGained
        if (edtCode.getText().equals("Código do Aparelho")) {
            edtCode.setText("");
        }
    }//GEN-LAST:event_edtCodeFocusGained

    private void edtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCodeFocusLost
        if (edtCode.getText().trim().isEmpty()) {
            edtCode.setText("Código do Aparelho");
        }
    }//GEN-LAST:event_edtCodeFocusLost

    private void btnPronto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPronto2MouseClicked
        if(doPointValidations()){
            Point p =  new Point();
            p.setCode(Integer.parseInt(edtCode.getText()));
            p.setLocale(edtLocation.getText());
            if(p.Create()){
                actHome h = new actHome();
                h.setLogin(edtLogin.getText());
                h.setDoInstruciton(true);
                this.dispose();
                h.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnPronto2MouseClicked

    private void btnPronto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPronto2MouseEntered
        btnPronto2.setForeground(new Color(220, 255, 255));
        pnPronto2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPronto2MouseEntered

    private void btnPronto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPronto2MouseExited
        btnPronto2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnPronto2MouseExited

    public void setAllToInvisible() {

        lblSubTitle.setVisible(false);
        lblNotice.setVisible(false);
        btnExit.setVisible(false);
        pnBackground.setVisible(false);
        pnAdmin.setVisible(false);
        pnPoint.setVisible(false);
    }

    public void doAnimation(int pAnimation) {
        setAllToInvisible();
        new Thread() {
            public void run() {
                int x = 0;
                while (x <= 255) {
                    Color Degradation = new Color(255, 255, 255, x);
                    lblTitle.setForeground(Degradation);
                    x += 2;
                    try {
                        sleep(7);
                    } catch (InterruptedException ex) {
                    }
                }
                x = 0;
                lblSubTitle.setVisible(true);
                while (x <= 255) {
                    Color Degradation = new Color(255, 255, 255, x);
                    lblSubTitle.setForeground(Degradation);
                    x += 2;
                    try {
                        sleep(7);
                    } catch (InterruptedException ex) {
                    }
                }
                if (pAnimation == 0) {
                    x = 0;
                    btnExit.setVisible(true);
                    while (x <= 255) {
                        Color Degradation = new Color(255, 255, 255, x);
                        btnExit.setForeground(Degradation);
                        x += 2;
                        try {
                            sleep(1);
                        } catch (InterruptedException ex) {
                        }
                    }
                }
                switch (pAnimation) {
                    case 0:
                        doCompanyAnimation();
                        break;
                    case 1:
                        doAdminAnimation();
                        break;
                    default:
                        doPointAnimation();
                        break;
                }
            }
        }.start();
    }

    public void doCompanyAnimation() {
        new Thread() {
            public void run() {
                int x = 0;
                pnBackground.setVisible(true);
                while (x <= 255) {
                    pnBackground.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255, x), 2, true));
                    Border borderTextField = BorderFactory.createLineBorder(new Color(255, 255, 255, x), 1, true);
                    Color Degradation = new Color(255, 255, 255, x);
                    edtCNPJ.setBorder(borderTextField);
                    edtNumber.setBorder(borderTextField);
                    edtCompanyName.setBorder(borderTextField);
                    edtStreet.setBorder(borderTextField);
                    pnPronto.setBorder(borderTextField);

                    x += 2;
                    try {
                        sleep(7);
                        edtCNPJ.setForeground(Degradation);
                        edtNumber.setForeground(Degradation);
                        edtCompanyName.setForeground(Degradation);
                        edtStreet.setForeground(Degradation);
                        btnPronto.setForeground(Degradation);
                        lblCNPJ.setForeground(Degradation);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }.start();
    }

    public void doAdminAnimation() {
        new Thread() {
            public void run() {
                int x = 0;
                pnAdmin.setVisible(true);
                while (x <= 255) {
                    pnAdmin.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255, x), 2, true));
                    Border borderTextField = BorderFactory.createLineBorder(new Color(255, 255, 255, x), 1, true);
                    Color Degradation = new Color(255, 255, 255, x);
                    edtCPF.setBorder(borderTextField);
                    edtPassword.setBorder(borderTextField);
                    edtLogin.setBorder(borderTextField);
                    pnPronto1.setBorder(borderTextField);

                    x += 2;
                    try {
                        sleep(7);
                        edtCPF.setForeground(Degradation);
                        edtLogin.setForeground(Degradation);
                        edtPassword.setForeground(Degradation);
                        btnPronto1.setForeground(Degradation);
                        lblCPF.setForeground(Degradation);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }.start();
    }

    public void doPointAnimation() {
        new Thread() {
            public void run() {
                int x = 0;
                pnPoint.setVisible(true);
                while (x <= 255) {
                    pnPoint.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255, x), 2, true));
                    Border borderTextField = BorderFactory.createLineBorder(new Color(255, 255, 255, x), 1, true);
                    Color Degradation = new Color(255, 255, 255, x);
                    edtCode.setBorder(borderTextField);
                    edtLocation.setBorder(borderTextField);
                    pnPronto2.setBorder(borderTextField);

                    x += 2;
                    try {
                        sleep(7);
                        lblNotice.setVisible(true);
                        lblNotice.setForeground(Degradation);
                        edtCode.setForeground(Degradation);
                        edtLocation.setForeground(Degradation);
                        btnPronto2.setForeground(Degradation);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }.start();
    }

    public boolean doCompanyValidations() {
        if (CheckCompanyIsEmpty()) {
            actAlert obA = new actAlert();
            obA.setVisible(true);
            return false;
        } else if (CheckNumber(edtNumber.getText())) {
            actAlert obA = new actAlert();
            obA.lbMsg.setText("<html><p align=\"center\">O campo Número<br>deve ser um Número!</p></html>");
            obA.setVisible(true);
            return false;
        } else if (CheckCNPJ() == false) {
            actAlert obA = new actAlert();
            obA.lbMsg.setText("<html><p align=\"center\">O CNPJ Informado<br>é inválido!</p></html>");
            obA.setVisible(true);
            return false;
        } else {
            return true;
        }
    }

    public boolean CheckCompanyIsEmpty() {
        if ((edtCompanyName.getText().trim().isEmpty()) || (edtCompanyName.getText().equals("Nome da Empresa"))) {
            edtCompanyName.requestFocus();
            return true;
        } else if ((edtNumber.getText().trim().isEmpty()) || (edtNumber.getText().equals("Número"))) {
            edtNumber.requestFocus();
            return true;
        } else if ((edtStreet.getText().trim().isEmpty()) || (edtStreet.getText().equals("Rua"))) {
            edtStreet.requestFocus();
            return true;
        } else if (edtCNPJ.getText().equals("  .   .   /    -  ")) {
            edtCNPJ.requestFocus();
            return true;
        } else {
            return false;
        }
    }

    public boolean CheckNumber(String TestingNumber) {
        int Number = 0;
        try {
            Number = Integer.parseInt(TestingNumber);
        } catch (NumberFormatException e) {
            return true;
        }
        return false;
    }

    public boolean CheckCNPJ() {
        Company c = new Company();
        return c.isCNPJ(((edtCNPJ.getText().replace(".", "")).replace("/", "")).replace("-", ""));
    }

    public boolean doAdminValidations() {
        if (CheckAdminIsEmpty()) {
            actAlert obA = new actAlert();
            obA.setVisible(true);
            return false;
        } else if (!CheckCPF()) {
            actAlert obA = new actAlert();
            obA.lbMsg.setText("<html><p align=\"center\">O CPF Informado<br>é inválido!</p></html>");
            obA.setVisible(true);
            return false;
        } else {
            return true;
        }
    }

    public boolean CheckAdminIsEmpty() {
        if ((edtLogin.getText().trim().isEmpty()) || (edtLogin.getText().equals("Login"))) {
            edtLogin.requestFocus();
            return true;
        } else if ((edtPassword.getText().trim().isEmpty()) || (edtPassword.getText().equals("Senha"))) {
            edtPassword.requestFocus();
            return true;
        } else if (edtCPF.getText().equals("   .   .   -  ")) {
            edtCPF.requestFocus();
            return true;
        } else {
            return false;
        }
    }

    public boolean CheckCPF() {
        Admin a = new Admin();
        return a.isCPF((edtCPF.getText().replace(".", "").replace("-", "")));
    }
    
    public boolean doPointValidations() {
        if (CheckPointIsEmpty()) {
            actAlert obA = new actAlert();
            obA.setVisible(true);
            return false;
        } else {
            return true;
        }
    }
    
    public boolean CheckPointIsEmpty() {
        if ((edtCode.getText().trim().isEmpty()) || (edtCode.getText().equals("Código do Aparelho"))) {
            edtCode.requestFocus();
            return true;
        } else if ((edtLocation.getText().trim().isEmpty()) || (edtLocation.getText().equals("Local"))) {
            edtLocation.requestFocus();
            return true;
        } else if (CheckNumber(edtCode.getText())) {
            actAlert obA = new actAlert();
            obA.lbMsg.setText("<html><p align=\"center\">O campo Código<br>deve ser um Número!</p></html>");
            obA.setVisible(true);
            return false;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actFirstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actFirstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actFirstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actFirstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actFirstLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnPronto;
    private javax.swing.JLabel btnPronto1;
    private javax.swing.JLabel btnPronto2;
    private javax.swing.JFormattedTextField edtCNPJ;
    private javax.swing.JFormattedTextField edtCPF;
    private javax.swing.JTextField edtCode;
    private javax.swing.JTextField edtCompanyName;
    private javax.swing.JTextField edtLocation;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JTextField edtNumber;
    private javax.swing.JTextField edtPassword;
    private javax.swing.JTextField edtStreet;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNotice;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnAdmin;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JPanel pnPoint;
    private javax.swing.JPanel pnPronto;
    private javax.swing.JPanel pnPronto1;
    private javax.swing.JPanel pnPronto2;
    // End of variables declaration//GEN-END:variables
}
