/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activitys;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import mecsystem.Classes.Admin;

/**
 *
 * @author Aluno
 */
public class actReadAdmin extends javax.swing.JDialog {

    /**
     * Creates new form actReadAdmin
     */
    String SelectedParameter;
    boolean Verify;

    public actReadAdmin() {
        initComponents();
        background.setBackground(Color.white);        
        background.requestFocus();
        tbAdmin.getColumnModel().getColumn(0).setPreferredWidth(150);
        tbAdmin.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbAdmin.getColumnModel().getColumn(2).setPreferredWidth(150);
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        edtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAdmin = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Cancelar");
        btnBack.setToolTipText("Voltar");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pesquisa de Admnistrador");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, -1));

        edtSearch.setBackground(new java.awt.Color(51, 170, 236));
        edtSearch.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        edtSearch.setForeground(new java.awt.Color(255, 255, 255));
        edtSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtSearch.setText("Pesquisar por Nome");
        edtSearch.setToolTipText("Pesquisar");
        edtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        edtSearch.setOpaque(false);
        edtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtSearchFocusLost(evt);
            }
        });
        edtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtSearchKeyPressed(evt);
            }
        });
        getContentPane().add(edtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 430, 40));

        tbAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tbAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CPF", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 120, 450, 260));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/searchbackgroundadm.png"))); // NOI18N
        background.setOpaque(true);
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backgroundMouseMoved(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Verify = false;
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBack.setForeground(new Color(200, 255, 255));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBackMouseExited

    private void edtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusGained
        if (edtSearch.getText().equals("Pesquisar por Nome")) {
            edtSearch.setText("");
        }
    }//GEN-LAST:event_edtSearchFocusGained

    private void edtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusLost
        if (edtSearch.getText().trim().isEmpty()) {
            edtSearch.setText("Pesquisar por Nome");
        }
    }//GEN-LAST:event_edtSearchFocusLost

    private void edtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSearchKeyPressed
        Admin a = new Admin();
        a.setLoginAdmin(edtSearch.getText());
        ResultSet rs = a.Read();

        DefaultTableModel model = (DefaultTableModel) tbAdmin.getModel();
        model.setNumRows(0);
        try {
            while (rs.next()) {
                model.addRow(new String[]{
                    rs.getString("idtb_admin"),
                    rs.getString("CpfAdmin"),
                    rs.getString("AdminName")
                });
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_edtSearchKeyPressed

    private void tbAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAdminMouseClicked
        SelectedParameter = tbAdmin.getValueAt(tbAdmin.getSelectedRow(), 2).toString();
        Verify = true;
        this.dispose();
    }//GEN-LAST:event_tbAdminMouseClicked

    private void backgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseMoved

    }//GEN-LAST:event_backgroundMouseMoved

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked

    }//GEN-LAST:event_backgroundMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actReadAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actReadAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actReadAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actReadAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actReadAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnBack;
    private javax.swing.JTextField edtSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tbAdmin;
    // End of variables declaration//GEN-END:variables
}
