/*
 * ControlePonto_v2.0
 * Cedup Hermmann Hering 20/04/19
 * @MecSystem
 */
package Activitys;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author LOL
 */
public class actSettings extends javax.swing.JFrame {

    /**
     * Creates new form actLogin
     */
    public actSettings() {
        initComponents();
        this.setLocationRelativeTo(null);   //Centraliza a Tela
        imgBackground.requestFocus();
        pnAdminSettings.setVisible(false);
        pnFunctionsSettings.setVisible(false);
        pnPointSettings.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        pnSettings = new javax.swing.JPanel();
        pnOption1 = new javax.swing.JPanel();
        btnPoint = new javax.swing.JLabel();
        pnOption2 = new javax.swing.JPanel();
        btnFunctions = new javax.swing.JLabel();
        pnOption3 = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JLabel();
        pnAdminSettings = new javax.swing.JPanel();
        pnDeleteAdmin = new javax.swing.JPanel();
        btnDeleteAdmin = new javax.swing.JLabel();
        pnUpdateAdmin = new javax.swing.JPanel();
        btnUpdateAdmin = new javax.swing.JLabel();
        pnCreateAdmin = new javax.swing.JPanel();
        btnCreateAdmin = new javax.swing.JLabel();
        pnBackAdmin = new javax.swing.JPanel();
        btnBackAdmin = new javax.swing.JLabel();
        pnFunctionsSettings = new javax.swing.JPanel();
        pnDeleteFunction = new javax.swing.JPanel();
        btnDeleteFunction = new javax.swing.JLabel();
        pnUpdateFunction = new javax.swing.JPanel();
        btnUpdateFunction = new javax.swing.JLabel();
        pnCreateFunction = new javax.swing.JPanel();
        btnCreateFunction = new javax.swing.JLabel();
        pnBackFunction = new javax.swing.JPanel();
        btnBackFunction = new javax.swing.JLabel();
        pnPointSettings = new javax.swing.JPanel();
        pnDeletePoint = new javax.swing.JPanel();
        btnDeletePoint = new javax.swing.JLabel();
        pnUpdatePoint = new javax.swing.JPanel();
        btnUpdatePoint = new javax.swing.JLabel();
        pnCreatePoint = new javax.swing.JPanel();
        btnCreatePoint = new javax.swing.JLabel();
        pnBackPoint = new javax.swing.JPanel();
        btnBackPoint = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Voltar");
        btnBack.setToolTipText("Voltar");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnSettings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnSettings.setOpaque(false);
        pnSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnOption1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnOption1.setOpaque(false);
        pnOption1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPoint.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnPoint.setForeground(new java.awt.Color(255, 255, 255));
        btnPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPoint.setText("Gerenciar Pontos");
        btnPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPointMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPointMouseExited(evt);
            }
        });
        pnOption1.add(btnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnSettings.add(pnOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 428, 50));

        pnOption2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnOption2.setOpaque(false);
        pnOption2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFunctions.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnFunctions.setForeground(new java.awt.Color(255, 255, 255));
        btnFunctions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFunctions.setText("Gerenciar Funções");
        btnFunctions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFunctionsMouseExited(evt);
            }
        });
        pnOption2.add(btnFunctions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnSettings.add(pnOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 428, 50));

        pnOption3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnOption3.setOpaque(false);
        pnOption3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdmin.setText("Gerenciar Administradores");
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminMouseExited(evt);
            }
        });
        pnOption3.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnSettings.add(pnOption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        getContentPane().add(pnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 428, 420));

        pnAdminSettings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnAdminSettings.setOpaque(false);
        pnAdminSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnDeleteAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnDeleteAdmin.setOpaque(false);
        pnDeleteAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeleteAdmin.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnDeleteAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteAdmin.setText("Excluir Administrador");
        btnDeleteAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteAdminMouseExited(evt);
            }
        });
        pnDeleteAdmin.add(btnDeleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnAdminSettings.add(pnDeleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 428, 50));

        pnUpdateAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnUpdateAdmin.setOpaque(false);
        pnUpdateAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateAdmin.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnUpdateAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdateAdmin.setText("Alterar Administrador");
        btnUpdateAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateAdminMouseExited(evt);
            }
        });
        pnUpdateAdmin.add(btnUpdateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnAdminSettings.add(pnUpdateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 428, 50));

        pnCreateAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnCreateAdmin.setOpaque(false);
        pnCreateAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateAdmin.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnCreateAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreateAdmin.setText("Cadastrar Administrador");
        btnCreateAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateAdminMouseExited(evt);
            }
        });
        pnCreateAdmin.add(btnCreateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnAdminSettings.add(pnCreateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnBackAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnBackAdmin.setOpaque(false);
        pnBackAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackAdmin.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnBackAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnBackAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBackAdmin.setText("Voltar");
        btnBackAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackAdminMouseExited(evt);
            }
        });
        pnBackAdmin.add(btnBackAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnAdminSettings.add(pnBackAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 428, 50));

        getContentPane().add(pnAdminSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 428, 420));

        pnFunctionsSettings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnFunctionsSettings.setOpaque(false);
        pnFunctionsSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnDeleteFunction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnDeleteFunction.setOpaque(false);
        pnDeleteFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeleteFunction.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnDeleteFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFunction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeleteFunction.setText("Excluir Função");
        btnDeleteFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteFunctionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteFunctionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteFunctionMouseExited(evt);
            }
        });
        pnDeleteFunction.add(btnDeleteFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnFunctionsSettings.add(pnDeleteFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 428, 50));

        pnUpdateFunction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnUpdateFunction.setOpaque(false);
        pnUpdateFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateFunction.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnUpdateFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateFunction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdateFunction.setText("Alterar Função");
        btnUpdateFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateFunctionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateFunctionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateFunctionMouseExited(evt);
            }
        });
        pnUpdateFunction.add(btnUpdateFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnFunctionsSettings.add(pnUpdateFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 428, 50));

        pnCreateFunction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnCreateFunction.setOpaque(false);
        pnCreateFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateFunction.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnCreateFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateFunction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreateFunction.setText("Cadastrar Função");
        btnCreateFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateFunctionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateFunctionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateFunctionMouseExited(evt);
            }
        });
        pnCreateFunction.add(btnCreateFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnFunctionsSettings.add(pnCreateFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnBackFunction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnBackFunction.setOpaque(false);
        pnBackFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackFunction.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnBackFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnBackFunction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBackFunction.setText("Voltar");
        btnBackFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackFunctionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackFunctionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackFunctionMouseExited(evt);
            }
        });
        pnBackFunction.add(btnBackFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnFunctionsSettings.add(pnBackFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 428, 50));

        getContentPane().add(pnFunctionsSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 428, 420));

        pnPointSettings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnPointSettings.setOpaque(false);
        pnPointSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnDeletePoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnDeletePoint.setOpaque(false);
        pnDeletePoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeletePoint.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnDeletePoint.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletePoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeletePoint.setText("Excluir Ponto");
        btnDeletePoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletePointMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletePointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletePointMouseExited(evt);
            }
        });
        pnDeletePoint.add(btnDeletePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnPointSettings.add(pnDeletePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 428, 50));

        pnUpdatePoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnUpdatePoint.setOpaque(false);
        pnUpdatePoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdatePoint.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnUpdatePoint.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdatePoint.setText("Alterar Ponto");
        btnUpdatePoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdatePoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdatePointMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdatePointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdatePointMouseExited(evt);
            }
        });
        pnUpdatePoint.add(btnUpdatePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnPointSettings.add(pnUpdatePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 428, 50));

        pnCreatePoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnCreatePoint.setOpaque(false);
        pnCreatePoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreatePoint.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnCreatePoint.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreatePoint.setText("Cadastrar Ponto");
        btnCreatePoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreatePoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreatePointMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreatePointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreatePointMouseExited(evt);
            }
        });
        pnCreatePoint.add(btnCreatePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnPointSettings.add(pnCreatePoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnBackPoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pnBackPoint.setOpaque(false);
        pnBackPoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackPoint.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        btnBackPoint.setForeground(new java.awt.Color(255, 255, 255));
        btnBackPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBackPoint.setText("Voltar");
        btnBackPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackPointMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackPointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackPointMouseExited(evt);
            }
        });
        pnBackPoint.add(btnBackPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 428, 50));

        pnPointSettings.add(pnBackPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 428, 50));

        getContentPane().add(pnPointSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 428, 420));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 40)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Configurações");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 828, -1));

        lblVersion.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setText("v 3.0");
        getContentPane().add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, -1, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Activitys/images/background.jpg"))); // NOI18N
        imgBackground.setToolTipText("");
        imgBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBackgroundMouseClicked(evt);
            }
        });
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBackMouseEntered

    private void imgBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBackgroundMouseClicked
        imgBackground.requestFocus();
    }//GEN-LAST:event_imgBackgroundMouseClicked

    private void btnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseEntered
        btnAdmin.setForeground(new Color(200,255,255));
        btnAdmin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAdminMouseEntered

    private void btnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseExited
        btnAdmin.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnAdminMouseExited

    private void btnFunctionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseEntered
        btnFunctions.setForeground(new Color(200,255,255));
        btnFunctions.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnFunctionsMouseEntered

    private void btnFunctionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseExited
        btnFunctions.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnFunctionsMouseExited

    private void btnPointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPointMouseEntered
        btnPoint.setForeground(new Color(200,255,255));
        btnPoint.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPointMouseEntered

    private void btnPointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPointMouseExited
        btnPoint.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnPointMouseExited

    private void btnDeleteAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAdminMouseEntered
        btnDeleteAdmin.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnDeleteAdminMouseEntered

    private void btnDeleteAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAdminMouseExited
        btnDeleteAdmin.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnDeleteAdminMouseExited

    private void btnUpdateAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateAdminMouseEntered
        btnUpdateAdmin.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnUpdateAdminMouseEntered

    private void btnUpdateAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateAdminMouseExited
        btnUpdateAdmin.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnUpdateAdminMouseExited

    private void btnCreateAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAdminMouseEntered
        btnCreateAdmin.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnCreateAdminMouseEntered

    private void btnCreateAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAdminMouseExited
        btnCreateAdmin.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnCreateAdminMouseExited

    private void btnBackAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackAdminMouseEntered
        btnBackAdmin.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnBackAdminMouseEntered

    private void btnBackAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackAdminMouseExited
        btnBackAdmin.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnBackAdminMouseExited

    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
        pnSettings.setVisible(false);
        pnAdminSettings.setVisible(true);
    }//GEN-LAST:event_btnAdminMouseClicked

    private void btnDeleteFunctionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteFunctionMouseEntered
        btnDeleteFunction.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnDeleteFunctionMouseEntered

    private void btnDeleteFunctionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteFunctionMouseExited
        btnDeleteFunction.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnDeleteFunctionMouseExited

    private void btnUpdateFunctionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateFunctionMouseEntered
        btnUpdateFunction.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnUpdateFunctionMouseEntered

    private void btnUpdateFunctionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateFunctionMouseExited
        btnUpdateFunction.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnUpdateFunctionMouseExited

    private void btnCreateFunctionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateFunctionMouseEntered
        btnCreateFunction.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnCreateFunctionMouseEntered

    private void btnCreateFunctionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateFunctionMouseExited
        btnCreateFunction.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnCreateFunctionMouseExited

    private void btnBackFunctionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackFunctionMouseEntered
        btnBackFunction.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnBackFunctionMouseEntered

    private void btnBackFunctionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackFunctionMouseExited
        btnBackFunction.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnBackFunctionMouseExited

    private void btnBackAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackAdminMouseClicked
        pnAdminSettings.setVisible(false);
        pnSettings.setVisible(true);
    }//GEN-LAST:event_btnBackAdminMouseClicked

    private void btnBackFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackFunctionMouseClicked
        pnFunctionsSettings.setVisible(false);
        pnSettings.setVisible(true);
    }//GEN-LAST:event_btnBackFunctionMouseClicked

    private void btnFunctionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFunctionsMouseClicked
        pnSettings.setVisible(false);
        pnFunctionsSettings.setVisible(true);
    }//GEN-LAST:event_btnFunctionsMouseClicked

    private void btnDeletePointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePointMouseEntered
        btnDeletePoint.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnDeletePointMouseEntered

    private void btnDeletePointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePointMouseExited
        btnDeletePoint.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnDeletePointMouseExited

    private void btnUpdatePointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePointMouseEntered
        btnUpdatePoint.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnUpdatePointMouseEntered

    private void btnUpdatePointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePointMouseExited
        btnUpdatePoint.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnUpdatePointMouseExited

    private void btnCreatePointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatePointMouseEntered
        btnCreatePoint.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnCreatePointMouseEntered

    private void btnCreatePointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatePointMouseExited
        btnCreatePoint.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnCreatePointMouseExited

    private void btnBackPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPointMouseClicked
        pnPointSettings.setVisible(false);
        pnSettings.setVisible(true);
    }//GEN-LAST:event_btnBackPointMouseClicked

    private void btnBackPointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPointMouseEntered
        btnBackPoint.setForeground(new Color(200,255,255));
    }//GEN-LAST:event_btnBackPointMouseEntered

    private void btnBackPointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPointMouseExited
        btnBackPoint.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnBackPointMouseExited

    private void btnPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPointMouseClicked
        pnSettings.setVisible(false);
        pnPointSettings.setVisible(true);
    }//GEN-LAST:event_btnPointMouseClicked

    private void btnCreateAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAdminMouseClicked
        new actCreateAdmin().setVisible(true);
    }//GEN-LAST:event_btnCreateAdminMouseClicked

    private void btnUpdateAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateAdminMouseClicked
        new actUpdateAdmin().setVisible(true);
    }//GEN-LAST:event_btnUpdateAdminMouseClicked

    private void btnDeleteAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAdminMouseClicked
        new actDeleteAdmin().setVisible(true);
    }//GEN-LAST:event_btnDeleteAdminMouseClicked

    private void btnDeleteFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteFunctionMouseClicked
        new actDeleteFunction().setVisible(true);
    }//GEN-LAST:event_btnDeleteFunctionMouseClicked

    private void btnUpdateFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateFunctionMouseClicked
        new actUpdateFunction().setVisible(true);
    }//GEN-LAST:event_btnUpdateFunctionMouseClicked

    private void btnCreateFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateFunctionMouseClicked
        new actCreateFunction().setVisible(true);
    }//GEN-LAST:event_btnCreateFunctionMouseClicked

    private void btnDeletePointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePointMouseClicked
        new actDeletePoint().setVisible(true);
    }//GEN-LAST:event_btnDeletePointMouseClicked

    private void btnUpdatePointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePointMouseClicked
        new actUpdatePoint().setVisible(true);
    }//GEN-LAST:event_btnUpdatePointMouseClicked

    private void btnCreatePointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatePointMouseClicked
        new actCreatePoint().setVisible(true);
    }//GEN-LAST:event_btnCreatePointMouseClicked

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdmin;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBackAdmin;
    private javax.swing.JLabel btnBackFunction;
    private javax.swing.JLabel btnBackPoint;
    private javax.swing.JLabel btnCreateAdmin;
    private javax.swing.JLabel btnCreateFunction;
    private javax.swing.JLabel btnCreatePoint;
    private javax.swing.JLabel btnDeleteAdmin;
    private javax.swing.JLabel btnDeleteFunction;
    private javax.swing.JLabel btnDeletePoint;
    private javax.swing.JLabel btnFunctions;
    private javax.swing.JLabel btnPoint;
    private javax.swing.JLabel btnUpdateAdmin;
    private javax.swing.JLabel btnUpdateFunction;
    private javax.swing.JLabel btnUpdatePoint;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnAdminSettings;
    private javax.swing.JPanel pnBackAdmin;
    private javax.swing.JPanel pnBackFunction;
    private javax.swing.JPanel pnBackPoint;
    private javax.swing.JPanel pnCreateAdmin;
    private javax.swing.JPanel pnCreateFunction;
    private javax.swing.JPanel pnCreatePoint;
    private javax.swing.JPanel pnDeleteAdmin;
    private javax.swing.JPanel pnDeleteFunction;
    private javax.swing.JPanel pnDeletePoint;
    private javax.swing.JPanel pnFunctionsSettings;
    private javax.swing.JPanel pnOption1;
    private javax.swing.JPanel pnOption2;
    private javax.swing.JPanel pnOption3;
    private javax.swing.JPanel pnPointSettings;
    private javax.swing.JPanel pnSettings;
    private javax.swing.JPanel pnUpdateAdmin;
    private javax.swing.JPanel pnUpdateFunction;
    private javax.swing.JPanel pnUpdatePoint;
    // End of variables declaration//GEN-END:variables
}
